FROM java

LABEL maintainer "bird"

COPY /project/target/*.war /usr/src/myapp/app.war

WORKDIR /usr/src/myapp/

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JHIPSTER_SLEEP=0 \
    JAVA_OPTS="-Dspring.profiles.active=stg"
    
    
ENTRYPOINT java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar "app.war" "$@"
EXPOSE 8080
