FROM java

LABEL maintainer "bird"

COPY /project/target/*.war /usr/src/myapp/app.war

# 复制数据库初始化脚本create_table.sql到/docker-entrypoint-initdb.d文件夹下
COPY /project/sql/*.sql /docker-entrypoint-initdb.d

WORKDIR /usr/src/myapp/

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JHIPSTER_SLEEP=0 \
    JAVA_OPTS="-Dspring.profiles.active=stg"
    
    
ENTRYPOINT java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar "app.war" "$@"
EXPOSE 8080
