version: '2'
services:
    findmusic-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        # volumes:
        #     - ~/volumes/jhipster/findmusic/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 59200:9200
            - 59300:9300
        environment:
            - cluster.name=elasticsearch
            - network.host=0.0.0.0
            - discovery.type=single-node
        #command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node